classes:
  - 'freedomfi.common'
  - 'helm.jenkins'
parameters:
  jenkins: 
    admin:
      username: ?{gpg:freedomfi/jenkins/admin/username}
      password: ?{gpg:freedomfi/jenkins/admin/password}

    installPlugins:
      - kubernetes:1.27.6
      - workflow-aggregator:2.6
      - git:4.4.5
      - configuration-as-code:1.46

  kapitan:
    vars:
      target: cicd
